// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations;

namespace Domain.Models;

public partial class AuditLog
{
    [Key]
    public int AuditLogId { get; set; }

    [Required, MaxLength(100)]
    public string TableName { get; set; } = null!;

    public int? RecordId { get; set; }

    [Required, MaxLength(10)]
    public string Action { get; set; } = null!; // INSERT, UPDATE, DELETE

    public string? OldValues { get; set; } // JSON
    public string? NewValues { get; set; } // JSON

    public int? UserId { get; set; }

    // تأكد أن الاسم هنا ChangedAt ليطابق السكريبت الأخير
    public DateTime ChangedAt { get; set; } = DateTime.UtcNow;
}