// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class AuditLog
{
    public int AuditLogId { get; set; }

    public string TableName { get; set; }

    public int RecordId { get; set; }

    public string Action { get; set; }

    public string OldValues { get; set; }

    public string NewValues { get; set; }

    public int? UserId { get; set; }

    public DateTime Timestamp { get; set; }

    public string IpAddress { get; set; }

    public string UserAgent { get; set; }
}