// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq.Expressions;

namespace Domain.Models;

public partial class BroadcastWorkflowDBContext : DbContext
{

    // ✅ هذا هو الكونستراكتور المطلوب حصراً ليعمل مع IDBContextFactory
    public BroadcastWorkflowDBContext(DbContextOptions<BroadcastWorkflowDBContext> options)
        : base(options) // <--- السحر كله في تمرير الـ options للكلاس الأساسي
    {
    }

    // استخدام التعبير البدني (Expression-bodied) لتعريف الـ DbSets (أمان أكثر)
    public virtual DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public virtual DbSet<Correspondent> Correspondents => Set<Correspondent>();
    public virtual DbSet<CorrespondentCoverage> CorrespondentCoverages => Set<CorrespondentCoverage>();
    public virtual DbSet<Episode> Episodes => Set<Episode>();
    public virtual DbSet<EpisodeStatus> EpisodeStatuses => Set<EpisodeStatus>();
    public virtual DbSet<EpisodeGuest> EpisodeGuests => Set<EpisodeGuest>();
    public virtual DbSet<ExecutionLog> ExecutionLogs => Set<ExecutionLog>();
    public virtual DbSet<Guest> Guests => Set<Guest>();
    public virtual DbSet<Program> Programs => Set<Program>();
    public virtual DbSet<PublishingLog> PublishingLogs => Set<PublishingLog>();
    public virtual DbSet<Role> Roles => Set<Role>();
    public virtual DbSet<User> Users => Set<User>();
    public virtual DbSet<Permission> Permissions => Set<Permission>();
    public virtual DbSet<RolePermission> RolePermissions => Set<RolePermission>();


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // ✨ السحر هنا: تطبيق كل الإعدادات من مجلد Configurations تلقائياً
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(BroadcastWorkflowDBContext).Assembly);

        // تطبيق الـ Seed Data للـ EpisodeStatus
        modelBuilder.Entity<EpisodeStatus>().HasData(
            new EpisodeStatus { StatusId = 0, StatusName = "Planned", DisplayName = "مجدولة", SortOrder = 0 },
            new EpisodeStatus { StatusId = 1, StatusName = "Executed", DisplayName = "منفّذة", SortOrder = 1 },
            new EpisodeStatus { StatusId = 2, StatusName = "Published", DisplayName = "منشورة", SortOrder = 2 },
            new EpisodeStatus { StatusId = 3, StatusName = "Cancelled", DisplayName = "ملغاة", SortOrder = 3 }
        );


        // ✨ إصلاح خلل الحذف المنطقي: تطبيق الفلتر على أي كيان يرث من BaseEntity
        foreach (var entityType in modelBuilder.Model.GetEntityTypes())
        {
            if (typeof(BaseEntity).IsAssignableFrom(entityType.ClrType))
            {
                modelBuilder.Entity(entityType.ClrType).HasQueryFilter(
                    GenerateSoftDeleteFilter(entityType.ClrType)
                );
            }
        }


        OnModelCreatingPartial(modelBuilder);
    }

    // دالة مساعدة لبناء فلتر الحذف المنطقي ديناميكياً لكل كيان
    private static LambdaExpression GenerateSoftDeleteFilter(Type entityType)
    {
        var parameter = System.Linq.Expressions.Expression.Parameter(entityType, "e");
        var property = System.Linq.Expressions.Expression.Property(parameter, nameof(BaseEntity.IsActive));
        var condition = System.Linq.Expressions.Expression.Equal(property, System.Linq.Expressions.Expression.Constant(true));
        return System.Linq.Expressions.Expression.Lambda(condition, parameter);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    private void ConfigureAuditRelationships<T>(ModelBuilder modelBuilder) where T : BaseEntity
    {
        modelBuilder.Entity<T>()
            .HasOne(e => e.CreatedByUser)
            .WithMany()
            .HasForeignKey(e => e.CreatedByUserId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<T>()
            .HasOne(e => e.UpdatedByUser)
            .WithMany()
            .HasForeignKey(e => e.UpdatedByUserId)
            .OnDelete(DeleteBehavior.Restrict);

        // ✨ السطر الجديد: تطبيق الفلترة العالمية لعدم جلب المحذوفات منطقياً أبداً
        modelBuilder.Entity<T>().HasQueryFilter(e => e.IsActive);

    }


    // View DTOs for EF mapping
    public record ActiveEpisodeView(int EpisodeId, string EpisodeName, string ProgramName, DateTime? ScheduledExecutionTime, DateTime? ActualExecutionTime, string StatusText, string? SpecialNotes, DateTime CreatedAt);
    public record ActiveGuestView(int GuestId, string FullName, string? Organization, string? PhoneNumber, string? EmailAddress, int EpisodeCount);
    public record TodayEpisodeView(int EpisodeId, string EpisodeName, string ProgramName, DateTime? ScheduledExecutionTime, string? GuestNames, string StatusText);


}
