// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Domain.Models;

public partial class Episode : BaseEntity
{
    public int EpisodeId { get; set; }

    public int ProgramId { get; set; }

    public int? GuestId { get; set; }

    public string EpisodeName { get; set; }

    public string EpisodeDescription { get; set; }

    public DateTime? ScheduledExecutionTime { get; set; }

    public DateTime? ActualExecutionTime { get; set; }

    //public byte Status { get; set; }

    public string SpecialNotes { get; set; }

    // ✅ نشر الموقع
    public bool IsWebsitePublished { get; set; }

    // ✅ أضف هذين السطرين مكانه:
    public byte StatusId { get; set; }

    [ForeignKey("StatusId")]
    public virtual EpisodeStatus EpisodeStatus { get; set; } = null!;

    public virtual ICollection<EpisodeGuest> EpisodeGuests { get; set; } = new List<EpisodeGuest>();

    public virtual ICollection<ExecutionLog> ExecutionLogs { get; set; } = new List<ExecutionLog>();

    public virtual Program Program { get; set; }

    public virtual ICollection<PublishingLog> PublishingLogs { get; set; } = new List<PublishingLog>();
}