// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class EpisodeGuest
{
    public int EpisodeGuestId { get; set; }

    public int EpisodeId { get; set; }

    public int GuestId { get; set; }

    public string BookingNotes { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public int? CreatedByUserId { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual Episode Episode { get; set; }

    public virtual Guest Guest { get; set; }
}