// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Domain.Models;

public partial class EpisodeGuest : BaseEntity
{
    public int EpisodeGuestId { get; set; }

    public int EpisodeId { get; set; }

    public int GuestId { get; set; }

    public string BookingNotes { get; set; }

    public virtual Episode Episode { get; set; }

    public virtual Guest Guest { get; set; }
}