// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Guest : BaseEntity
{
    public int GuestId { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public string Bio { get; set; }

    public string Organization { get; set; }

    public string Website { get; set; }

    public string PhoneNumber { get; set; }

    public string EmailAddress { get; set; }

    public string Twitter { get; set; }

    public string Instagram { get; set; }

    public string TikTok { get; set; }

    public string LinkedIn { get; set; }

    public string YouTube { get; set; }

    public string SpecialNotes { get; set; }

    public virtual ICollection<CorrespondentCoverage> CorrespondentCoverages { get; set; } = new List<CorrespondentCoverage>();

    public virtual ICollection<EpisodeGuest> EpisodeGuests { get; set; } = new List<EpisodeGuest>();
}