// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class PublishingLog
{
    public int PublishingLogId { get; set; }

    public int EpisodeId { get; set; }

    public int PublishedByUserId { get; set; }

    public string YouTubeUrl { get; set; }

    public string TwitterUrl { get; set; }

    public string FacebookUrl { get; set; }

    public string SoundCloudUrl { get; set; }

    public DateTime PublishedAt { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual Episode Episode { get; set; }

    public virtual User PublishedByUser { get; set; }
}