// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class VwActiveGuest
{
    public int GuestId { get; set; }

    public string FullName { get; set; }

    public string Organization { get; set; }

    public string PhoneNumber { get; set; }

    public string EmailAddress { get; set; }

    public int? EpisodeCount { get; set; }
}