// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class VwTodayEpisode
{
    public int EpisodeId { get; set; }

    public string EpisodeName { get; set; }

    public string ProgramName { get; set; }

    public DateTime? ScheduledExecutionTime { get; set; }

    public string GuestNames { get; set; }

    public string StatusText { get; set; }
}